# ===================================================================
# Spring Boot configuration for the "cloudfoundry" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

#eureka:
#    instance:
#        prefer-ip-address: false
#        hostname: ${vcap.application.uris[0]}
#        nonSecurePort: 80
server:
    port: 8080
logging:
    level:
        com.bmcd.asset.health: DEBUG
        io.github.jhipster: DEBUG
#jhipster:
#    registry:
#        password: GoshawkRules!
spring:
    cloud:
        services:
            registrationMethod: direct
uaa:
    oauth-authentication-parameters:
        -
            name:  Goshawk AAD
            url: https://login.microsoftonline.com/bfbb9a2b-6d99-4e78-b3c7-95005d555c8b/oauth2/v2.0/token
            client-id: 98e0d32c-4ffd-4238-a258-888179a861c8
            application-id: 98e0d32c-4ffd-4238-a258-888179a861c8
    oauth-authorization-parameters:
        -
            name:  Goshawk Single-Tenant - Test
            url:  https://login.microsoftonline.com/
            tenant-id:  bfbb9a2b-6d99-4e78-b3c7-95005d555c8b
            client-id:  ec1e1b1e-6afc-47d9-b592-8d9000d338ad
            client-secret:  u3Uibp+V*8HsNt@V}WuCAIom&cm1ERpE$2cP)O$t*_
#
            
